// Copyright 2014 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'diagnostics_tree.dart';
import 'error.dart';
import 'find.dart';
import 'frame_sync.dart';
import 'geometry.dart';
import 'gesture.dart';
import 'health.dart';
import 'layer_tree.dart';
import 'message.dart';
import 'render_tree.dart';
import 'request_data.dart';
import 'screenshot.dart';
import 'semantics.dart';
import 'text.dart';
import 'text_input_action.dart';
import 'wait.dart';

/// A factory for deserializing [SerializableFinder]s.
mixin DeserializeFinderFactory {
  /// Deserializes the finder from JSON generated by [SerializableFinder.serialize].
  SerializableFinder deserializeFinder(Map<String, String> json) {
<<<<<<< HEAD
    return switch (json['finderType']) {
      'ByType' => ByType.deserialize(json),
      'ByValueKey' => ByValueKey.deserialize(json),
      'ByTooltipMessage' => ByTooltipMessage.deserialize(json),
      'BySemanticsLabel' => BySemanticsLabel.deserialize(json),
      'ByText' => ByText.deserialize(json),
      'PageBack' => const PageBack(),
      'Descendant' => Descendant.deserialize(json, this),
      'Ancestor' => Ancestor.deserialize(json, this),
      _ => throw DriverError('Unsupported search specification type ${json['finderType']}'),
    };
=======
    final String? finderType = json['finderType'];
    switch (finderType) {
      case 'ByType': return ByType.deserialize(json);
      case 'ByValueKey': return ByValueKey.deserialize(json);
      case 'ByTooltipMessage': return ByTooltipMessage.deserialize(json);
      case 'BySemanticsLabel': return BySemanticsLabel.deserialize(json);
      case 'ByText': return ByText.deserialize(json);
      case 'PageBack': return const PageBack();
      case 'Descendant': return Descendant.deserialize(json, this);
      case 'Ancestor': return Ancestor.deserialize(json, this);
    }
    throw DriverError('Unsupported search specification type $finderType');
>>>>>>> 0a545b201052d8de3d0d76a04bc0911a062242c8
  }
}

/// A factory for deserializing [Command]s.
mixin DeserializeCommandFactory {
  /// Deserializes the finder from JSON generated by [Command.serialize] or [CommandWithTarget.serialize].
  Command deserializeCommand(Map<String, String> params, DeserializeFinderFactory finderFactory) {
<<<<<<< HEAD
    return switch (params['command']) {
      'get_health' => GetHealth.deserialize(params),
      'get_layer_tree' => GetLayerTree.deserialize(params),
      'get_render_tree' => GetRenderTree.deserialize(params),
      'enter_text' => EnterText.deserialize(params),
      'send_text_input_action' => SendTextInputAction.deserialize(params),
      'get_text' => GetText.deserialize(params, finderFactory),
      'request_data' => RequestData.deserialize(params),
      'scroll' => Scroll.deserialize(params, finderFactory),
      'scrollIntoView' => ScrollIntoView.deserialize(params, finderFactory),
      'set_frame_sync' => SetFrameSync.deserialize(params),
      'set_semantics' => SetSemantics.deserialize(params),
      'set_text_entry_emulation' => SetTextEntryEmulation.deserialize(params),
      'tap' => Tap.deserialize(params, finderFactory),
      'waitFor' => WaitFor.deserialize(params, finderFactory),
      'waitForAbsent' => WaitForAbsent.deserialize(params, finderFactory),
      'waitForTappable' => WaitForTappable.deserialize(params, finderFactory),
      'waitForCondition' => WaitForCondition.deserialize(params),
      'waitUntilNoTransientCallbacks' => WaitForCondition.deserialize(params),
      'waitUntilNoPendingFrame' => WaitForCondition.deserialize(params),
      'waitUntilFirstFrameRasterized' => WaitForCondition.deserialize(params),
      'get_semantics_id' => GetSemanticsId.deserialize(params, finderFactory),
      'get_offset' => GetOffset.deserialize(params, finderFactory),
      'get_diagnostics_tree' => GetDiagnosticsTree.deserialize(params, finderFactory),
      'screenshot' => ScreenshotCommand.deserialize(params),
      final String? kind => throw DriverError('Unsupported command kind $kind'),
    };
=======
    final String? kind = params['command'];
    switch (kind) {
      case 'get_health': return GetHealth.deserialize(params);
      case 'get_layer_tree': return GetLayerTree.deserialize(params);
      case 'get_render_tree': return GetRenderTree.deserialize(params);
      case 'enter_text': return EnterText.deserialize(params);
      case 'send_text_input_action': return SendTextInputAction.deserialize(params);
      case 'get_text': return GetText.deserialize(params, finderFactory);
      case 'request_data': return RequestData.deserialize(params);
      case 'scroll': return Scroll.deserialize(params, finderFactory);
      case 'scrollIntoView': return ScrollIntoView.deserialize(params, finderFactory);
      case 'set_frame_sync': return SetFrameSync.deserialize(params);
      case 'set_semantics': return SetSemantics.deserialize(params);
      case 'set_text_entry_emulation': return SetTextEntryEmulation.deserialize(params);
      case 'tap': return Tap.deserialize(params, finderFactory);
      case 'waitFor': return WaitFor.deserialize(params, finderFactory);
      case 'waitForAbsent': return WaitForAbsent.deserialize(params, finderFactory);
      case 'waitForTappable': return WaitForTappable.deserialize(params, finderFactory);
      case 'waitForCondition': return WaitForCondition.deserialize(params);
      case 'waitUntilNoTransientCallbacks': return WaitForCondition.deserialize(params);
      case 'waitUntilNoPendingFrame': return WaitForCondition.deserialize(params);
      case 'waitUntilFirstFrameRasterized': return WaitForCondition.deserialize(params);
      case 'get_semantics_id': return GetSemanticsId.deserialize(params, finderFactory);
      case 'get_offset': return GetOffset.deserialize(params, finderFactory);
      case 'get_diagnostics_tree': return GetDiagnosticsTree.deserialize(params, finderFactory);
    }

    throw DriverError('Unsupported command kind $kind');
>>>>>>> 0a545b201052d8de3d0d76a04bc0911a062242c8
  }
}
